service: aws-serverless-notes
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: Johan-Skola
  region: eu-north-1

functions:
  getNotes:
    handler: handlers/getNotes.handler
    events:
      - http:
          path: api/notes
          method: get
          authorizer: aws_iam
  postNotes:
    handler: handlers/postNotes.handler
    events:
      - http:
          path: api/notes
          method: post
          authorizer: aws_iam
          
resources:
  Resources:
    MyDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: myNotesTable         