service: aws-serverless-notes
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: Johan-Skola
  region: eu-north-1
  iam:
    role:arn:aws:iam::396249927244:user/Johan-Skola

plugins:
  - serverless-webpack

package:
  individually: true



functions:
  getNotes:
    handler: functions/getNotes/index.handler
    events:
      - http:
          path: api/notes
          method: get
  putNotes:
    handler: functions/patchNotes/index.handler
    events:
      - http:
          path: api/notes
          method: put        
  postNotes:
    handler: functions/postNotes/index.handler
    events:
      - http:
          path: api/notes
          method: post
  signup:
    handler: functions/signUp/index.handler
    events:
      - http:
          path: api/user/signup
          method: post
  login:
    handler: functions/login/index.handler
    events:
      - http:
          path: api/user/login
          method: post
  deleteNotes:
    handler: functions/deleteNotes/index.handler
    events:
      - http:
          path: api/notes
          method: delete       
          
resources:
  Resources:
    MyDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: myNotesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S   # Om det 채r en str채ng
            # eller AttributeType: N om det 채r en nummer
        KeySchema:
          - AttributeName: id
            KeyType: HASH   # Anv채nd noteId som huvudnyckel
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    usersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: accounts
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST